language: minimal
dist: focal
before-script:
  - git clone https://github.com/verilator/verilator.git
  - unset VERILATOR_ROOT
  - pushd verilator && git checkout v4.110 && autoconf && ./configure && make -j && sudo make install
script:
  - verilator -version
  - make
  - cmp -s logs/output.txt test_vectors/keccak_ref_out.txt