# Generated by vmake version 2.2

# Define path to each library
LIB_SV_STD = /pkgs/mentor/questa/10.2a/questasim/linux/../sv_std
LIB_WORK = work

# Define path to each design unit
SV_STD__std = $(LIB_SV_STD)/_lib.qdb
WORK__tb_keccak_sv_unit = $(LIB_WORK)/tb_keccak_sv_unit/_primary.dat
WORK__tb_keccak = $(LIB_WORK)/tb_keccak/_primary.dat
WORK__prog_keccak = $(LIB_WORK)/prog_keccak/_primary.dat
WORK__pkg_keccak = $(LIB_WORK)/pkg_keccak/_primary.dat
WORK__keccak_sv_unit = $(LIB_WORK)/keccak_sv_unit/_primary.dat
WORK__keccak_round_sv_unit = $(LIB_WORK)/keccak_round_sv_unit/_primary.dat
WORK__keccak_round_constants_gen_sv_unit = $(LIB_WORK)/keccak_round_constants_gen_sv_unit/_primary.dat
WORK__keccak_round_constant_gen = $(LIB_WORK)/keccak_round_constant_gen/_primary.dat
WORK__keccak_round = $(LIB_WORK)/keccak_round/_primary.dat
WORK__keccak_buffer_sv_unit = $(LIB_WORK)/keccak_buffer_sv_unit/_primary.dat
WORK__keccak_buffer = $(LIB_WORK)/keccak_buffer/_primary.dat
WORK__keccak = $(LIB_WORK)/keccak/_primary.dat
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

sim_output.txt: whole_library 
	vsim -64 -c -do "run 99999999999ms" -voptargs="+acc" tb_keccak -l $@

whole_library :     $(WORK__tb_keccak_sv_unit) \
    $(WORK__tb_keccak) \
    $(WORK__prog_keccak) \
    $(WORK__pkg_keccak) \
    $(WORK__keccak_sv_unit) \
    $(WORK__keccak_round_sv_unit) \
    $(WORK__keccak_round_constants_gen_sv_unit) \
    $(WORK__keccak_round_constant_gen) \
    $(WORK__keccak_round) \
    $(WORK__keccak_buffer_sv_unit) \
    $(WORK__keccak_buffer) \
    $(WORK__keccak)

$(WORK__keccak) \
$(WORK__keccak_buffer) \
$(WORK__keccak_buffer_sv_unit) \
$(WORK__keccak_round) \
$(WORK__keccak_round_constant_gen) \
$(WORK__keccak_round_constants_gen_sv_unit) \
$(WORK__keccak_round_sv_unit) \
$(WORK__keccak_sv_unit) \
$(WORK__pkg_keccak) \
$(WORK__tb_keccak) \
$(WORK__tb_keccak_sv_unit) \
$(WORK__prog_keccak) : work \
		 pkg_keccak.sv \
		 tb_keccak.sv \
		 prog_keccak.sv \
		 keccak.sv \
		 keccak_round.sv \
		 keccak_round_constants_gen.sv \
		 keccak_buffer.sv \
		$(SV_STD__std)
	$(VLOG) -L mtiAvm -L mtiOvm -L mtiUvm \
		 -L mtiUPF pkg_keccak.sv \
		 tb_keccak.sv \
		 prog_keccak.sv \
		 keccak.sv \
		 keccak_round.sv \
		 keccak_round_constants_gen.sv \
		 keccak_buffer.sv

.PHONY: work
work:
	vlib work
	vmap work work
